Repository TEAM-DDIS/be14-fin-DDIS-FE, pull requests merged in 2025-06, with the labels that each got.

#42 [STYLE] 라우터 주석 해제
  src/router/index.js
Labels: 🎨 Style

#43 [FEAT] 조직 구조 편집 기능 구현 및 사이드바 수정
  public/org.json
  src/App.vue
  src/assets/main.css
  src/components/org/appointment/Appointment.vue
  src/components/org/appointment/AppointmentDetail.vue
  src/components/org/appointment/RegisterAppointment.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/introduction/Introduction.vue
  src/components/org/introduction/JobDetail.vue
  src/components/org/structure/EditHierarchy.vue
  src/components/org/structure/EditStructure.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/HierarchyAll.vue
  src/components/org/structure/Structure.vue
  src/components/sidebar/SubSidebar.vue
  src/main.js
  src/router/index.js
Labels: ✨ Feat

#61 [FEAT] 조직 및 직무 전체 페이지 수정
  src/assets/main.css
  src/components/org/appointment/Appointment.vue
  src/components/org/appointment/AppointmentDetail.vue
  src/components/org/appointment/RegisterAppointment.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/EditHierarchy.vue
  src/components/org/structure/EditStructure.vue
  src/components/org/structure/Structure.vue
Labels: ✨ Feat

#64 [FEAT] 공지사항 상세 조회 페이지 구현
  src/components/post/PostDetailPage.vue
  src/components/post/PostEnroll.vue
  src/components/post/PostListPage.vue
  src/router/index.js
Labels: ✨ Feat

#67 [STYLE] login 화면 style 변경
  src/assets/icons/pizza-icon2.svg
  src/components/login/LoginPage.vue
Labels: 🎨 Style

#72 [FEAT] 출퇴근 관리 페이지 구현
  package-lock.json
  public/attendance.json
  src/components/attendance/TeamWorkStatus.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/TodayMeetingCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/commute/AllCommuteCard.vue
  src/components/commute/EmployeeInfo.vue
  src/components/commute/MyCommuteCard.vue
  src/components/commute/MyCommuteSummary.vue
  src/components/commute/OtherCommuteCard.vue
  src/components/commute/OtherCommuteSummary.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/pages/AllCommutePage.vue
  src/pages/MyCommutePage.vue
  src/pages/OtherCommutePage.vue
  src/router/index.js
Labels: ✨ Feat

#77 [FEAT] 출근 정정 관리 페이지 구현
  public/attendance.json
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/CorrectionApproveEvent.vue
  src/components/correction/CorrectionRegistEvent.vue
  src/components/correction/CorrectionRejectEvent.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/pages/AllCorrectionPage.vue
  src/pages/MyCorrectionPage.vue
  src/router/index.js
Labels: ✨ Feat

#81 [FEAT] 전자결재 기안함 화면 구현
  src/components/draftdoc/MyDraft.vue
Labels: ✨ Feat

#82 [REFACTOR] 백엔드 연결을 위한 성과 등록 코드 수정
  package-lock.json
  package.json
  src/components/Goals/GoalListPage.vue
Labels: 🔧 Refactor

#83 [STYLE] 근태 관리 스타일 컨벤션 반영
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/MeetingEventCard.vue
  src/components/attendance/PersonalEventCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/commute/AllCommuteCard.vue
  src/components/commute/MyCommuteCard.vue
  src/components/commute/OtherCommuteCard.vue
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/CorrectionApproveEvent.vue
  src/components/correction/CorrectionRegistEvent.vue
  src/components/correction/CorrectionRejectEvent.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/components/leave/DateFilter.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/pages/attendance/AllCommutePage.vue
  src/pages/attendance/AllCorrectionPage.vue
  src/pages/attendance/AllLeavePage.vue
  src/pages/attendance/MyAttendancePage.vue
  src/pages/attendance/MyCommutePage.vue
  src/pages/attendance/MyCorrectionPage.vue
  src/pages/attendance/MyLeavePage.vue
  src/pages/attendance/OtherCommutePage.vue
  src/pages/attendance/TeamAttendancePage.vue
  src/router/index.js
Labels: 🎨 Style

#85 [FEAT] 퇴직금 지급 현황 구현 (상세보기 전)
  src/components/salary/retirement/RetirementPaymentStatus.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementEstimate.vue
  src/pages/salary/RetirementPaymentStatus.vue
  src/router/index.js
Labels: ⚙ Chore, ✨ Feat

#86 [FEAT] 조직 및 직무 페이지 통일 수정
  package-lock.json
  src/assets/main.css
  src/components/grid/BaseGrid.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/DeleteModal.vue
  src/pages/org/AppointmentDetailPage.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/IntroductionPage.vue
  src/pages/org/JobDetailPage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
  src/router/index.js
Labels: ✨ Feat

#88 [FEAT] 전자결재 문서함 화면 구현 및 컴포넌트, 페이지 분리
  src/components/draftdoc/forms/DraftFormA.vue
  src/components/draftdoc/forms/DraftFormB.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/eapproval/ApproveDoc.vue
  src/pages/eapproval/DraftTemplateList.vue
  src/pages/eapproval/InBox.vue
  src/pages/eapproval/MyDraft.vue
  src/pages/eapproval/ReferenceDoc.vue
  src/pages/eapproval/TemporaryDoc.vue
  src/router/index.js
Labels: ⚙ Chore, ✨ Feat

#96 [FEAT] 퇴직금 명세서 모달 및 기능 구현
  src/components/salary/PayrollModal.vue
  src/components/salary/RetirementModal.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementPaymentStatus.vue
Labels: 🔧 Refactor, ✨ Feat

#101 [Refactor] 백엔드 연동 코드 리팩토링
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/HierarchyAll.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/JobDetailPage.vue
  src/pages/org/StructurePage.vue
Labels: 🔧 Refactor

#103 [FEAT] 예상 퇴직금 계산 화면 구현
  src/components/salary/PayrollModal.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementEstimate.vue
  src/pages/salary/RetirementPaymentStatus.vue
  src/router/index.js
Labels: 🔧 Refactor, ✨ Feat

#104 [REFACTOR] 오늘 팀 근태 현황, 회의 일정 조회 백엔드 연동
  src/components/attendance/TeamWorkStatus.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/TodayMeetingCard.vue
  src/pages/attendance/TeamAttendancePage.vue
Labels: 🔧 Refactor

#106 [FEAT] 전체 평가 조회하는 페이지 구현
  package-lock.json
  package.json
  src/components/Evaluation/EvaluationPage.vue
  src/components/Goals/GoalDetailPage.vue
  src/components/Goals/GoalListPage.vue
  src/components/login/LoginPage.vue
  src/pages/achievment/AchievmentPage.vue
  src/router/index.js
Labels: ✨ Feat

#107 [FEAT] 조직 등록 및 삭제 모달 백엔드 연동
  src/components/org/structure/AddModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/Hierarchy.vue
  src/pages/org/AppointmentDetailPage.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
  src/router/index.js
Labels: ✨ Feat

#108 [REFACTOR] 출퇴근 백엔드 연동
  src/components/attendance/AttendanceSummaryCard.vue
Labels: 🔧 Refactor

#109 [FEAT] 성과 이력 페이지 제작, 내가 평가한 평가 페이지 제작
  src/components/Evaluation/MyEvalsPage.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/achievment/AchievmentPage.vue
  src/router/index.js
Labels: ✨ Feat

#110 [REFACTOR] 개인/팀 근태 현황 + 사이드 출퇴근 카드 백엔드 연동
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/sidebar/AttendanceCard.vue
Labels: 🔧 Refactor

#112 [FEAT] 자주 쓰는 메뉴 모달 구현
  package.json
  src/components/home/FavoriteMenu.vue
  src/components/home/MenuModal.vue
  src/components/home/MenuSidebar.vue
  src/components/home/MenuSubSidebar.vue
  src/pages/MainPage.vue
Labels: ⚙ Chore, ✨ Feat

#118 [REFACTOR] 타이머 로직, 캘린더 스타일 변경
  package-lock.json
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
Labels: ✨ Feat

#117 [FEAT] 조직 및 직무 백엔드 연동 및 화면 수정
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/EditHierarchy.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/HierarchyAll.vue
  src/pages/org/AppointmentDetailPage.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/StructurePage.vue
Labels: ✨ Feat

#119 [REFACTOR] 주간 초과 근무 현황 백엔드 연동
  src/components/attendance/WeeklyOvertimeCard.vue
  src/pages/attendance/MyAttendancePage.vue
Labels: 🔧 Refactor

#120 [FEAT] 인사발령 등록 백엔드 연동
  src/assets/main.css
  src/pages/org/RegisterAppointmentPage.vue
Labels: ✨ Feat

#122 [FEAT] 403, 404 page 구현
  public/images/erppizza_background.png
  src/App.vue
  src/pages/error/Error403.vue
  src/pages/error/Error404.vue
  src/router/index.js
Labels: ⚙ Chore, ✨ Feat

#125 [FEAT] 기안문 작성 백엔드 연동 중간 pr
  package-lock.json
  package.json
  public/mockup.json
  src/assets/icons/person-add.svg
  src/components/draftdoc/draftcreate/DraftTemplateList.vue
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/ApproveModal.vue
  src/components/eapproval/DraftSaveModal.vue
  src/components/eapproval/SubmitModal.vue
  src/components/sidebar/SubSidebar.vue
  src/main.js
  src/pages/eapproval/DetailTest.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/DraftFormB.vue
  src/pages/eapproval/DraftTemplateList.vue
  src/router/index.js
  vite.config.js
Labels: ✨ Feat

#127 [REFACTOR]결재라인 기안자 추가 및 결재선 지정 모달 구현
  src/components/eapproval/ApprovalLineModal.vue
  src/pages/eapproval/DraftFormA.vue
Labels: 🔧 Refactor

#128 [REFACTOR] 연차 관리 백엔드 연동
  package-lock.json
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/pages/attendance/AllLeavePage.vue
Labels: 🔧 Refactor

#129 [FEAT] 기안문 작성, 결재함 조회 백과 연동
  src/pages/eapproval/ApproveDoc.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/DraftFormB.vue
Labels: ✨ Feat

#130 [REFACTOR] 출퇴근 관리 백엔드 연동
  src/components/commute/AllCommuteCard.vue
  src/components/commute/EmployeeInfo.vue
  src/components/commute/MyCommuteCard.vue
  src/components/commute/MyCommuteSummary.vue
  src/components/commute/OtherCommuteCard.vue
  src/components/commute/OtherCommuteSummary.vue
  src/pages/attendance/AllCommutePage.vue
  src/pages/attendance/MyCommutePage.vue
  src/pages/attendance/OtherCommutePage.vue
Labels: 🔧 Refactor

#131 [FEAT] HOME 캘린더, 팀 근태 현황
  src/components/home/AttendanceBox.vue
  src/components/home/CalendarBox.vue
  src/components/home/FavoriteMenuBox.vue
  src/components/home/MyStatusBox.vue
  src/components/home/ReminderBox.vue
  src/pages/attendance/MyAttendancePage.vue
Labels: 🎨 Style, ✨ Feat

#132 [STYLE] erpizza 명칭 수정
  public/images/erpizza_background.png
  src/pages/error/Error403.vue
  src/pages/error/Error404.vue
Labels: 🎨 Style

#134 [REFACTOR] 전자결재 결재함 및 상세페이지 리팩토링
  src/components/eapproval/ApproveModal.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/eapproval/ApproveDoc.vue
  src/pages/eapproval/DetailTest.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/MyDraft.vue
  src/router/index.js
Labels: 🔧 Refactor

#139 [REFACTOR] 공지사항 목록 조회 백엔드 연동
  src/components/post/PostListPage.vue
Labels: ✨ Feat

#142 [REFACTOR] 출근 정정 관리 백엔드 연동
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/pages/attendance/AllCorrectionPage.vue
Labels: 🔧 Refactor

#147 [REFACTOR] 백엔드 연동
  src/components/post/PostDetailPage.vue
  src/components/post/PostEnroll.vue
  src/components/post/PostListPage.vue
Labels: ✨ Feat

#151 [REFACTOR] 사원 등록 수정
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/post/PostEnroll.vue
Labels: ✨ Feat

#154 [FEAT] 결재함 및 결재처리 구현/백엔드 연동
  src/components/eapproval/ApproveModal.vue
  src/pages/eapproval/ApproveDoc.vue
  src/pages/eapproval/DetailTest.vue
  src/pages/eapproval/DraftFormA.vue
Labels: ✨ Feat

#159 [FEAT] 징계 목록 조회 백엔드 연동
  src/components/employeeInfo/disciplinaryList.vue
Labels: 🔧 Refactor, ✨ Feat

#161 [FEAT] 챗봇 버튼 구현
  src/App.vue
  src/assets/icons/chat_logo.svg
  src/components/chatbot/ChatModal.vue
  src/components/chatbot/FloatingChat.vue
  src/components/chatbot/MessageBubble.vue
Labels: ✨ Feat

#162 [FEAT] 초과근무 신청 백엔드 연동
  src/components/attendance/OverTimeEventCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/commute/AllCommuteCard.vue
Labels: ✨ Feat

#166 [FEAT] 하이라키 부장 등록 가능하게 수정, 참조함 조회 등 구현
  src/assets/main.css
  src/components/Evaluation/EvaluationPage.vue
  src/components/Evaluation/MyEvalsPage.vue
  src/components/Goals/GoalListPage.vue
  src/components/Goals/MyPerfModal.vue
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/EHierarchy.vue
  src/components/filter/PerformanceContentFilter.vue
  src/components/filter/PerformanceHistory.vue
  src/components/filter/YearMonthFilter.vue
  src/components/org/appointment/OrgSelectorModal.vue
  src/components/org/structure/HierarchyAppointment.vue
  src/pages/achievment/AchievmentPage.vue
  src/pages/achievment/AchivementPageEmp.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/MyDraftBoxPage.vue
  src/pages/eapproval/ReceiverBoxPage.vue
  src/pages/eapproval/ReferenceBoxPage.vue
  src/pages/org/RegisterAppointmentPage.vue
Labels: ✨ Feat

#165 [REFACTOR] 급여 권한 설정
  src/components/salary/PayrollModal.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementEstimate.vue
  src/pages/salary/RetirementPaymentStatus.vue
Labels: 🔧 Refactor

#171 [FEAT] 징계 목록 내 파일 다운로드 구현
  src/components/employeeInfo/disciplinaryList.vue
Labels: ✨ Feat

#179 [REFACTOR] 권한 설정
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/TeamWorkStatus.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/TodayMeetingCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/commute/EmployeeInfo.vue
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/components/home/AttendanceBox.vue
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/components/sidebar/AttendanceCard.vue
  src/pages/attendance/AllCommutePage.vue
  src/pages/attendance/AllCorrectionPage.vue
  src/pages/attendance/AllLeavePage.vue
  src/pages/attendance/MyCommutePage.vue
  src/pages/attendance/OtherCommutePage.vue
Labels: 🔧 Refactor

#181 [FEAT] 전자결재 기안문서 회수 기능 백엔드 연동 구현
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/ApproveModal.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
Labels: ✨ Feat

#183 [FEAT] 본인 정보 수정 기능 구현
  src/components/employeeInfo/MyEmployeePage.vue
Labels: ✨ Feat

#187 [REFACTOR] 일정 수정, 삭제 기능 추가, 리팩토링
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/MeetingEventEditCard.vue
  src/components/attendance/PersonalEventEditCard.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/HomePersonalCalendar.vue
  src/components/calendar/HomeTeamCalendar.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/commute/EmployeeInfo.vue
  src/components/commute/MyCommuteCard.vue
  src/components/commute/MyCommuteSummary.vue
  src/components/commute/OtherCommuteCard.vue
  src/components/commute/OtherCommuteSummary.vue
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/CorrectionRegistEvent.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/pages/attendance/AllCommutePage.vue
  src/pages/attendance/AllCorrectionPage.vue
  src/pages/attendance/AllLeavePage.vue
  src/pages/attendance/MyAttendancePage.vue
  src/pages/attendance/MyCommutePage.vue
  src/pages/attendance/MyCorrectionPage.vue
  src/pages/attendance/MyLeavePage.vue
  src/pages/attendance/OtherCommutePage.vue
Labels: 🔧 Refactor, ✨ Feat

#189 [REFACTOR] 결재라인 다중선택 기능 및 상세페이지 리팩토링
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/EHierarchy.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
Labels: 🔧 Refactor

#192 [FEAT] 본인 정보 조회, 사원 정보 조회 내 인사발령 조회 및 상세 페이지 이동
  src/components/employeeInfo/ContractEnroll.vue
  src/components/employeeInfo/ContractList.vue
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/EmployeeList.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/components/employeeInfo/disciplinaryEnroll.vue
  src/components/employeeInfo/disciplinaryList.vue
  src/components/post/PostListPage.vue
Labels: ✨ Feat

#195 [REFACTOR] 인사팀 권한 설정
  src/components/employeeInfo/ContractList.vue
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeList.vue
  src/components/employeeInfo/disciplinaryList.vue
  src/components/post/PostDetailPage.vue
  src/components/post/PostListPage.vue
Labels: 🔧 Refactor

#196 [FEAT] 인사팀 권한 설정
  src/components/org/structure/AddModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/Hierarchy.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/IntroductionPage.vue
  src/pages/org/JobDetailPage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
Labels: ✨ Feat

#198 [STYLE] alert -> toast 일괄 적용
  src/components/salary/PayrollModal.vue
  src/components/salary/RetirementModal.vue
  src/components/toast/BaseToast.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementEstimate.vue
  src/pages/salary/RetirementPaymentStatus.vue
Labels: 🎨 Style, ✨ Feat

#207 [REFACTOR] 타이머 버그 수정
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/TeamWorkStatus.vue
Labels: 🔧 Refactor

#208 [STYLE] alert -> toast 일괄 적용
  src/components/org/appointment/ConfirmModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/EditHierarchy.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/RegisterAppointmentPage.vue
Labels: ✨ Feat

#209 [FEAT] 기안문 상세조회 내 수신자, 참조자 렌더링 구현
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/ReceiverBoxPage.vue
  src/pages/eapproval/ReferenceBoxPage.vue
Labels: ✨ Feat

#213 [REFACTOR] 챗봇 API 수정
  src/components/chatbot/ChatModal.vue
Labels: 🔧 Refactor

#214 [REFACTOR] alert -> toast
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/EmployeeList.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/pages/eapproval/DraftTempListPage.vue
Labels: 🔧 Refactor

#216 [REFACTOR] 리팩토링 항목 리팩토링
  src/components/employeeInfo/ContractEnroll.vue
  src/components/employeeInfo/ContractList.vue
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/components/employeeInfo/disciplinaryEnroll.vue
  src/components/employeeInfo/disciplinaryList.vue
  src/components/post/PostListPage.vue
Labels: 🔧 Refactor

#217 [REFACTOR] UI 리팩토링
  src/components/chatbot/ChatModal.vue
  src/components/chatbot/FloatingChat.vue
  src/components/chatbot/MessageBubble.vue
  src/components/home/ReminderBox.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
Labels: 🎨 Style, 🔧 Refactor

#228 [FEAT] 다크모드 일부 적용
  package-lock.json
  package.json
  src/App.vue
  src/assets/theme.css
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/MeetingEventCard.vue
  src/components/attendance/MeetingEventEditCard.vue
  src/components/attendance/OverTimeEventCard.vue
  src/components/attendance/PersonalEventCard.vue
  src/components/attendance/PersonalEventEditCard.vue
  src/components/attendance/TeamWorkStatus.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/TodayMeetingCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/chatbot/ChatModal.vue
  src/components/chatbot/MessageBubble.vue
  src/components/commute/AllCommuteCard.vue
  src/components/grid/BaseGrid.vue
  src/components/header/Header.vue
  src/components/home/AttendanceBox.vue
  src/components/home/CalendarBox.vue
  src/components/home/FavoriteMenuBox.vue
  src/components/home/MyStatusBox.vue
  src/components/home/NoticeBox.vue
  src/components/home/ReminderBox.vue
  src/components/home/menumodal/FavoriteMenu.vue
  src/components/home/menumodal/MenuModal.vue
  src/components/home/menumodal/MenuSidebar.vue
  src/components/home/menumodal/MenuSubSidebar.vue
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SubSidebar.vue
  src/main.js
Labels: 🎨 Style, 🔧 Refactor, ✨ Feat

#235 [REFACTOR] 2차 리팩토링
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/post/PostDetailPage.vue
Labels: 🔧 Refactor

#238 [REFACTPR] 프론트 디자인 통일
  api-docs.yaml
  src/components/Evaluation/EvaluationPage.vue
  src/components/Evaluation/MyEvalsPage.vue
  src/components/Goals/GoalListPage.vue
  src/components/Goals/MyPerfModal.vue
  src/components/header/Header.vue
  src/components/home/menumodal/MenuModal.vue
  src/components/login/LoginPage.vue
  src/components/sidebar/SubSidebar.vue
  src/constants/hronlypaths.js
  src/pages/achievment/AchievmentPage.vue
  src/router/index.js
  src/stores/draft.js
  src/stores/user.js
Labels: 🔧 Refactor

#239 [STYLE] 조직무, 근태, AG Grid 다크모드 적용
  src/assets/main.css
  src/assets/theme.css
  src/components/commute/AllCommuteCard.vue
  src/components/commute/MyCommuteCard.vue
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/correction/MyCorrectionRegistCard.vue
  src/components/correction/MyCorrectionUsedCard.vue
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/components/leave/DateFilter.vue
  src/components/leave/LeaveCountCard.vue
  src/components/leave/MyLeaveRegistCard.vue
  src/components/leave/MyLeaveUsedCard.vue
  src/main.js
  src/pages/attendance/AllCorrectionPage.vue
  src/pages/attendance/AllLeavePage.vue
  src/pages/attendance/MyCorrectionPage.vue
  src/pages/attendance/MyLeavePage.vue
  src/pages/org/AppointmentPage.vue
Labels: 🎨 Style

#241 [STYLE] 조직 및 직무 다크모드 AGAIN
  src/assets/theme.css
  src/components/eapproval/EHierarchy.vue
  src/components/notice/NoticeModal.vue
  src/components/org/appointment/ConfirmModal.vue
  src/components/org/appointment/GetEmployeeModal.vue
  src/components/org/appointment/OrgSelectorModal.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/CancelModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/EditHierarchy.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/HierarchyAppointment.vue
  src/pages/org/AppointmentDetailPage.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/IntroductionPage.vue
  src/pages/org/JobDetailPage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
Labels: 🎨 Style

#242 [REFATOR] 전자결재 리팩토링
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/ApproveModal.vue
  src/components/eapproval/DraftSaveModal.vue
  src/components/eapproval/RetrieveModal.vue
  src/components/eapproval/SubmitModal.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/eapproval/ApprovalBoxPage.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/MyDraftBoxPage.vue
  src/router/index.js
Labels: 🔧 Refactor

#244 [REFACTOR] 비회원 접근 차단, CSS 수정
  src/App.vue
  src/components/Evaluation/EvaluationPage.vue
  src/components/Evaluation/MyEvalsPage.vue
  src/components/Goals/GoalConfirmModal.vue
  src/components/Goals/GoalListPage.vue
  src/components/chatbot/ChatModal.vue
  src/pages/achievment/AchievmentPage.vue
  src/router/index.js
Labels: 🔧 Refactor

#248 [REFACTOR] 출력 값 불일치 제거
  src/components/employeeInfo/EmployeeDetailPage.vue
Labels: 🔧 Refactor

#252 [REFACTOR] 전자결재 리팩토링
  src/components/eapproval/ApprovalLineModal.vue
  src/pages/eapproval/ApprovalBoxPage.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/DraftFormC.vue
  src/pages/eapproval/DraftTempListPage.vue
  src/pages/eapproval/MyDraftBoxPage.vue
  src/pages/eapproval/ReceiverBoxPage.vue
  src/pages/eapproval/ReferenceBoxPage.vue
Labels: 🔧 Refactor

#253 [REFACTOR] 조직 및 직무 화면 수정
  src/components/org/appointment/GetHierarchy.vue
  src/components/org/structure/EditHierarchy.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/HierarchyAppointment.vue
  src/pages/org/EditStructurePage.vue
Labels: 🔧 Refactor

#254 [STYLE] 성과 다크모드 ING
  src/assets/theme.css
  src/components/Goals/GoalListPage.vue
  src/components/Goals/MyPerfModal.vue
  src/components/home/CalendarBox.vue
  src/components/home/FavoriteMenuBox.vue
Labels: 🎨 Style, 🔧 Refactor

#256 [REFACTOR] 인사정보 다크모드 및 레이아웃 수정
  src/assets/theme.css
  src/components/employeeInfo/ContractEnroll.vue
  src/components/employeeInfo/ContractList.vue
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/EmployeeList.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/components/employeeInfo/disciplinaryEnroll.vue
  src/components/employeeInfo/disciplinaryList.vue
  src/components/grid/BaseGrid.vue
  src/pages/org/RegisterAppointmentPage.vue
Labels: 🔧 Refactor

#258 [REFACTOR]
  src/components/salary/PayrollModal.vue
  src/pages/salary/PayrollSlip.vue
Labels: 🔧 Refactor

#259 [REFACTOR] 공지사항,용어사전 수정
  src/components/employeeInfo/disciplinaryEnroll.vue
  src/components/post/PostDetailPage.vue
  src/components/post/PostEnroll.vue
  src/components/post/PostListPage.vue
  src/pages/dictionary/DictionaryPage.vue
Labels: 🔧 Refactor

#260 [REFACTOR] 조직무 화면 수정
  src/components/header/Header.vue
  src/components/notice/NoticeModal.vue
  src/components/org/appointment/ConfirmModal.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/CancelModal.vue
  src/components/org/structure/DeleteModal.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/HierarchyAppointment.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
  src/stores/user.js
Labels: 🔧 Refactor

#262 [REFACTOR] 파일 업로드 버튼
  src/App.vue
  src/components/chatbot/ChatModal.vue
  src/components/chatbot/UploadModal.vue
  src/components/login/LoginPage.vue
Labels: 🔧 Refactor, ✨ Feat

#264 [REFACTOR] 프로필 사진 불러오기
  src/components/home/MyStatusBox.vue
  src/components/sidebar/SubSidebar.vue
  src/constants/hronlypaths.js
Labels: 🔧 Refactor

#265 [REFACTOR] 지급일 수정
  src/components/salary/PayrollModal.vue
  src/pages/salary/PayrollSlip.vue
  src/pages/salary/PayrollSlipIssue.vue
  src/pages/salary/RetirementPaymentStatus.vue
Labels: 🎨 Style, 🔧 Refactor

#267 [REFACTOR] 리팩토링 항목들 수정
  src/components/employeeInfo/ContractList.vue
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/components/employeeInfo/disciplinaryList.vue
  src/components/post/PostDetailPage.vue
Labels: 🔧 Refactor

#270 [STYLE] 공지사항 다크모드 적용
  src/components/post/PostDetailPage.vue
  src/components/post/PostListPage.vue
Labels: 🎨 Style, 🔧 Refactor

#271 [REFACTOR] 6/28 리팩토링
  src/components/employeeInfo/EmployeeDetailPage.vue
  src/components/employeeInfo/EmployeeEnroll.vue
  src/components/employeeInfo/EmployeeList.vue
  src/components/employeeInfo/MyEmployeePage.vue
  src/pages/dictionary/DictionaryPage.vue
Labels: 🔧 Refactor

#272 [REFACTOR] 수동 결재선 설정 기안자 지정 불가 예외처리
  src/components/eapproval/ApprovalLineModal.vue
Labels: 🔧 Refactor

#275 [REFACTOR] 피드백 수용하여 수정 완료
  index.html
  src/components/Evaluation/EvaluationPage.vue
  src/components/Evaluation/MyEvalsPage.vue
  src/components/Goals/GoalListPage.vue
  src/components/Goals/MyPerfModal.vue
  src/components/home/MyStatusBox.vue
  src/pages/achievment/AchievmentPage.vue
Labels: 🔧 Refactor

#277 [REFACTOR] 근태 리팩토링
  index.html
  public/images/pizza-icon2.svg
  src/components/attendance/OverTimeEventCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/commute/AllCommuteCard.vue
  src/components/correction/AllCorrectionRegistCard.vue
  src/components/correction/AllCorrectionUsedCard.vue
  src/components/leave/AllLeaveRegistCard.vue
  src/components/leave/AllLeaveUsedCard.vue
  src/pages/attendance/AllCorrectionPage.vue
  src/pages/attendance/AllLeavePage.vue
  src/pages/attendance/MyCorrectionPage.vue
  src/pages/attendance/MyLeavePage.vue
Labels: 🔧 Refactor

#281 [REFACTOR] 전자결재 리팩토링
  src/pages/eapproval/ApprovalBoxPage.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftFormA.vue
  src/pages/eapproval/MyDraftBoxPage.vue
Labels: 🔧 Refactor

#282 [REFACTOR] 다크모드 적용
  src/components/post/PostEnroll.vue
  src/components/post/PostListPage.vue
Labels: 🔧 Refactor

#283 [REFACTOR] 전자결재 리팩토링
  src/components/eapproval/ApproveModal.vue
  src/pages/eapproval/ApprovalBoxPage.vue
  src/pages/eapproval/DraftDetailPage.vue
  src/pages/eapproval/DraftTempListPage.vue
  src/pages/eapproval/MyDraftBoxPage.vue
  src/pages/eapproval/ReceiverBoxPage.vue
  src/pages/eapproval/ReferenceBoxPage.vue
Labels: 🔧 Refactor

#284 [REFACTOR] 조직무 화면 수정
  src/components/org/appointment/GetEmployeeModal.vue
  src/components/org/appointment/OrgSelectorModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/structure/AddModal.vue
  src/components/org/structure/HierarchyAppointment.vue
  src/pages/org/AppointmentPage.vue
  src/pages/org/EditStructurePage.vue
  src/pages/org/IntroductionPage.vue
  src/pages/org/JobDetailPage.vue
  src/pages/org/RegisterAppointmentPage.vue
  src/pages/org/StructurePage.vue
Labels: 🔧 Refactor

#286 [REFACTOR] 알림 링크 마진 수정
  src/components/notice/NoticeModal.vue
Labels: 🔧 Refactor

#288 [REFACTOR]가중치 계산 오류 수정
  src/components/Goals/GoalListPage.vue
  src/components/Goals/MyPerfModal.vue
Labels: 🔧 Refactor

#289 [REFACTOR] 퇴직금명세서 수정
  src/components/salary/RetirementModal.vue
Labels: 🔧 Refactor

#290 [REFACTOR] 전자결재 모달 오픈 시, 챗봇 비활성화
  src/components/eapproval/ApprovalLineModal.vue
  src/components/eapproval/ApproveModal.vue
  src/components/eapproval/DraftSaveModal.vue
  src/components/eapproval/RetrieveModal.vue
  src/components/eapproval/SubmitModal.vue
Labels: 🔧 Refactor

#291 no message
  src/components/Evaluation/EvaluationPage.vue
  src/components/sidebar/SubSidebar.vue
  src/router/index.js
Labels: 🔧 Refactor

#292 [REFACTOR] 조직무 모달 수정
  src/components/org/appointment/OrgSelectorModal.vue
  src/pages/org/RegisterAppointmentPage.vue
Labels: 🔧 Refactor
