Repository TEAM-DDIS/be14-fin-DDIS-FE, pull requests merged in 2025-05, with the labels that each got.

#4 Feat/goals
  .gitignore
  package-lock.json
  public/eval-data.json
  public/mockup.json
  src/App.vue
  src/component/EvaluationPage.vue
  src/component/GoalDetailPage.vue
  src/component/GoalListPage.vue
  src/components/sidebar/SubSidebar.vue
  src/main.js
  src/router/index.js
Labels: ✨ Feat

#11 [FEAT] 캘린더 컴포넌트 구현
  package-lock.json
  package.json
  public/schedule.json
  src/components/calendar/HomePersonalCalendar.vue
  src/components/calendar/HomeTeamCalendar.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/main.js
Labels: ✨ Feat

#14 [FEAT] 조직 및 직무 프론트 배경 수정
  server/db.json
  src/components/org/appointment/Appointment.vue
  src/components/org/introduction/Introduction.vue
  src/components/org/introduction/JobDetail.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/Structure.vue
  src/components/sidebar/AttendanceCard.vue
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SubSidebar.vue
Labels: ✨ Feat

#23 [REFACTOR] 화면 배율 고정
  index.html
  src/App.vue
  src/components/header/Header.vue
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SubSidebar.vue
  src/router/index.js
Labels: 🔧 Refactor

#29 [FEAT] 전자결재 기안작성 양식 선택 화면 구현
  src/assets/icons/angle-down.svg
  src/assets/icons/angle-up.svg
  src/assets/icons/search.svg
  src/components/draftdoc/draftcreate/DraftTemplateList.vue
  src/components/draftdoc/forms/DraftFormA.vue
  src/components/draftdoc/forms/DraftFormB.vue
  src/components/sidebar/SubSidebar.vue
  src/router/index.js
Labels: ✨ Feat

#31 [FEAT] 조직 소개 편집 모달 추가 및 grid css 설정
  public/org.json
  src/assets/icons/back_btn.svg
  src/assets/icons/detail_appointment.svg
  src/assets/icons/profile_img.svg
  src/assets/main.css
  src/components/grid/BaseGrid.vue
  src/components/org/appointment/Appointment.vue
  src/components/org/appointment/AppointmentDetail.vue
  src/components/org/appointment/RegisterAppointment.vue
  src/components/org/introduction/EditDeptModal.vue
  src/components/org/introduction/EditJobModal.vue
  src/components/org/introduction/Introduction.vue
  src/components/org/introduction/JobDetail.vue
  src/components/org/structure/Hierarchy.vue
  src/components/org/structure/Structure.vue
  src/main.js
  src/router/index.js
Labels: ✨ Feat

#32 [FEAT] 캘린더 수정
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/pages/MyAttendancePage.vue
  src/router/index.js
Labels: ✨ Feat

#34 [FEAT] 개인 일정 등록 구현
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/attendance/PersonalEventCard.vue
  src/components/attendance/WeeklyOvertimeCard.vue
  src/components/calendar/HomePersonalCalendar.vue
  src/components/calendar/HomeTeamCalendar.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/main.js
  src/pages/MyAttendancePage.vue
Labels: 🔧 Refactor, ✨ Feat

#36 [REFACTOR] 기안 작성시 양식 선택 화면 리팩토링
  src/components/draftdoc/draftcreate/DraftTemplateList.vue
  src/components/sidebar/SubSidebar.vue
  src/router/index.js
Labels: 🔧 Refactor

#39 [FEAT] 팀 근태 현황 페이지 구현
  public/attendance.json
  src/components/attendance/MeetingEventCard.vue
  src/components/attendance/TeamWorkStatus.vue
  src/components/attendance/TeamWorkStatusCard.vue
  src/components/attendance/TodayMeetingCard.vue
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/components/sidebar/SubSidebar.vue
  src/pages/MyAttendancePage.vue
  src/pages/TeamAttendancePage.vue
  src/router/index.js
Labels: ✨ Feat
